<?php
session_start();

// Check if user is logged in
if(!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit;
}

$user_name = $_SESSION['user_name'];
$login_time = date('Y-m-d H:i:s', $_SESSION['login_time'] ?? time());

// Set login time if not set
if(!isset($_SESSION['login_time'])) {
    $_SESSION['login_time'] = time();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Welcome Page</title>
    <link rel="stylesheet" href="style.css">
    <style>
        .welcome-container {
            max-width: 800px;
            margin: 50px auto;
        }
        .welcome-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            border-radius: 15px;
            text-align: center;
        }
        .info-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-top: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="welcome-container">
        <div class="welcome-header">
            <h1>🎉 Welcome, <?php echo $user_name; ?>!</h1>
            <p>This page is DYNAMICALLY generated by PHP based on YOUR login session</p>
        </div>
        
        <div class="info-card">
            <h3>📊 Your Session Information:</h3>
            <ul>
                <li><strong>User ID:</strong> <?php echo $_SESSION['user_id']; ?></li>
                <li><strong>Email:</strong> <?php echo $_SESSION['user_email']; ?></li>
                <li><strong>Logged in at:</strong> <?php echo $login_time; ?></li>
                <li><strong>Current server time:</strong> <?php echo date('Y-m-d H:i:s'); ?></li>
            </ul>
        </div>
        
        <div class="info-card">
            <h3>🔄 Server-Side Processing Demo:</h3>
            <p>The content of this page changes based on WHO is logged in:</p>
            <?php
            // Different messages based on user
            $hour = date('H');
            if($hour < 12) {
                echo "<p>☀️ Good morning, $user_name! Start your tasks today.</p>";
            } elseif($hour < 18) {
                echo "<p>🌤️ Good afternoon, $user_name! Keep making progress.</p>";
            } else {
                echo "<p>🌙 Good evening, $user_name! Great work today.</p>";
            }
            ?>
        </div>
        
        <div class="info-card">
            <h3>📚 Understanding Server-Side:</h3>
            <ul>
                <li><strong>Frontend (Browser):</strong> Shows this HTML/CSS</li>
                <li><strong>Backend (Server):</strong> PHP generated "<?php echo $user_name; ?>" from session</li>
                <li><strong>Dynamic Content:</strong> Time-based message changes automatically</li>
            </ul>
        </div>
        
        <div style="text-align: center; margin-top: 20px;">
            <a href="dashboard.php" style="background:#667eea; color:white; padding:10px 20px; text-decoration:none; border-radius:8px;">← Back to Dashboard</a>
            <a href="simple_form.html" style="background:#27ae60; color:white; padding:10px 20px; text-decoration:none; border-radius:8px; margin-left:10px;">Try Form Demo →</a>
        </div>
    </div>
</body>
</html>