<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Server Response - Backend Processing</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container response-container">
        <div class="success-box page-card">
            <h2>✅ SERVER RESPONSE RECEIVED</h2>
            <p>This page was generated by PHP on the <strong>BACKEND (SERVER)</strong></p>
        </div>

        <?php
        // This code runs on the SERVER (BACKEND)
        // It receives the POST request from simple_form.html
        
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            
            // Get data sent from the form
            $name = $_POST['user_name'];
            $technology = $_POST['technology'];
            $message = $_POST['message'];
            
            // Display what the server received
            echo '<div class="data-received">';
            echo '<h3>📥 DATA RECEIVED BY SERVER:</h3>';
            echo '<p><strong>POST Request Contents:</strong></p>';
            echo '<ul>';
            echo '<li>user_name = ' . htmlspecialchars($name) . '</li>';
            echo '<li>technology = ' . htmlspecialchars($technology) . '</li>';
            echo '<li>message = ' . htmlspecialchars($message) . '</li>';
            echo '</ul>';
            echo '<p><strong>Request Method:</strong> ' . $_SERVER['REQUEST_METHOD'] . '</p>';
            echo '<p><strong>Server Time:</strong> ' . date('Y-m-d H:i:s') . '</p>';
            echo '</div>';
            
            // Generate dynamic welcome message (BACKEND processing)
            echo '<div class="info-box">';
            echo '<h3>🎉 DYNAMIC WELCOME MESSAGE (Generated by PHP on Server)</h3>';
            echo '<p>Hello <strong>' . htmlspecialchars($name) . '</strong>!</p>';
            echo '<p>Great choice learning <strong>' . htmlspecialchars($technology) . '</strong>! ';
            echo 'This technology runs on the ' . ($technology == 'PHP' ? 'SERVER (BACKEND)' : 'BROWSER (FRONTEND)') . '.</p>';
            
            if (!empty($message)) {
                echo '<p><strong>Your message:</strong> "' . htmlspecialchars($message) . '"</p>';
            }
            
            echo '<p>Your form data was processed by <code>simple_processor.php</code> on the server.</p>';
            echo '</div>';
            
            // Show the request-response cycle explanation
            echo '<div class="info-box">';
            echo '<h3>🔄 REQUEST-RESPONSE CYCLE COMPLETED</h3>';
            echo '<ol>';
            echo '<li><strong>REQUEST:</strong> Your browser sent a POST request to this server</li>';
            echo '<li><strong>BACKEND:</strong> PHP processed the data using $_POST superglobal</li>';
            echo '<li><strong>RESPONSE:</strong> Server generated this HTML page with your data</li>';
            echo '<li><strong>DISPLAY:</strong> Your browser is now showing this response</li>';
            echo '</ol>';
            echo '</div>';
            
        } else {
            // If someone tries to access this file directly (not via form)
            echo '<div class="alert alert-error">';
            echo '<h3>⚠️ No form data received</h3>';
            echo '<p>This page should be accessed by submitting the form at <a href="simple_form.html">simple_form.html</a></p>';
            echo '<p>The server did not receive any POST data.</p>';
            echo '</div>';
        }
        ?>
        
        <div class="dashboard-footer">
            <a href="simple_form.html" class="footer-link">← Back to Form</a>
            <a href="dashboard.php" class="footer-link">Go to Dashboard</a>
        </div>
        
        <div class="info-box">            <h3>📚 What You Just Learned:</h3>
            <ul>
                <li><strong>Frontend:</strong> simple_form.html (runs in your browser)</li>
                <li><strong>Backend:</strong> simple_processor.php (runs on server)</li>
                <li><strong>Request:</strong> Browser sending POST data to server</li>
                <li><strong>Response:</strong> Server generating HTML and sending back</li>
                <li><strong>Form Submission:</strong> method="POST" sends data securely</li>
            </ul>
        </div>
    </div>
</body>
</html>