<?php
session_start();

// Check if user is logged in
if(!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit;
}

$user_name = $_SESSION['user_name'];
$login_time = date('Y-m-d H:i:s', $_SESSION['login_time'] ?? time());

// Set login time if not set
if(!isset($_SESSION['login_time'])) {
    $_SESSION['login_time'] = time();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dynamic Welcome Page</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container welcome-container">
        <div class="page-card welcome-header">
            <h1>🎉 Welcome, <?php echo $user_name; ?>!</h1>
            <p>This page is dynamically generated by PHP based on your session.</p>
        </div>
        
        <div class="page-card info-card">
            <h3>📊 Your Session Information</h3>
            <ul>
                <li><strong>User ID:</strong> <?php echo htmlspecialchars($_SESSION['user_id']); ?></li>
                <li><strong>Email:</strong> <?php echo htmlspecialchars($_SESSION['user_email']); ?></li>
                <li><strong>Logged in at:</strong> <?php echo htmlspecialchars($login_time); ?></li>
                <li><strong>Current server time:</strong> <?php echo htmlspecialchars(date('Y-m-d H:i:s')); ?></li>
            </ul>
        </div>
        
        <div class="page-card info-card">
            <h3>🔄 Server-Side Processing Demo</h3>
            <p>The content of this page changes based on who is logged in.</p>
            <?php
            $hour = date('H');
            if($hour < 12) {
                echo "<p>☀️ Good morning, " . htmlspecialchars($user_name) . "! Start your tasks today.</p>";
            } elseif($hour < 18) {
                echo "<p>🌤️ Good afternoon, " . htmlspecialchars($user_name) . "! Keep making progress.</p>";
            } else {
                echo "<p>🌙 Good evening, " . htmlspecialchars($user_name) . "! Great work today.</p>";
            }
            ?>
        </div>
        
        <div class="page-card info-card">
            <h3>📚 Understanding Server-Side</h3>
            <ul>
                <li><strong>Frontend (Browser):</strong> Shows this HTML/CSS.</li>
                <li><strong>Backend (Server):</strong> PHP generated "<?php echo htmlspecialchars($user_name); ?>" from session.</li>
                <li><strong>Dynamic Content:</strong> Time-based message changes automatically.</li>
            </ul>
        </div>
        
        <div class="dashboard-footer">
            <a href="dashboard.php" class="footer-link">← Back to Dashboard</a>
            <a href="simple_form.html" class="footer-link">Try Form Demo →</a>
        </div>
    </div>
</body>
</html>